name: Deploy App

on: 
  push: 
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
      SERVER_IP: ${{secrets.SERVER_IP}}
      NODE_OPTIONS: --max-old-space-size=2048
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install yarn -g
      - name: Build React App
        run: | 
          yarn install
          yarn build
      - name: Deploy
        run: |
          which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )
          eval $(ssh-agent -s)
          ssh-add <(echo "$SSH_PRIVATE_KEY" )
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          ssh root@$SERVER_IP 'rm -rf /var/www/html/fantasy.simoen.tech/*'
          scp -r build/* root@$SERVER_IP:/var/www/html/fantasy.simoen.tech/
