name: Deploy App

on: 
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install yarn -g
      - name: Build React App
        run: | 
          yarn install
          yarn build
